require 'rake/clean'
require 'cloudspin/stack/rake'

CLEAN.include('work')
CLEAN.include('.cloudspin/definitions')

include Cloudspin::Stack::Rake

StackTask.new(
  definition_location: 'https://github.com/cloudspinners/spin-stack-iam-roles/archive/master.zip'
)
