require 'rake/clean'
require 'cloudspin/stack/rake'
require 'fileutils'
require 'open-uri'
require 'tempfile'
require 'zip'

CLEAN.include('work')
CLEAN.include('.cloudspin/definitions')

include Cloudspin::Stack::Rake

StackTask.new(
  stack_name: 'bucket',
  definition_location: 'https://github.com/cloudspinners/spin-stack-s3bucket/archive/master.zip'
)
