require 'rake/clean'
require 'cloudspin/stack/rake'

CLEAN.include('work')
CLOBBER.include('state')

include Cloudspin::Stack::Rake

['sandbox', 'staging'].each { |environment|
  namespace "#{environment}" do
    stack = StackTask.new(environment).instance
    InspecTask.new(stack_instance: stack)
  end
}

namespace :all do
  desc 'Create all stacks'
  task :up => ['sandbox', 'staging'].map { |environment| :"#{environment}:up" }

  desc 'Destroy all stacks'
  task :down => ['sandbox', 'staging'].map { |environment| :"#{environment}:down" }
end
